USE my_db;

CREATE TABLE IF NOT EXISTS table1 (
    col1 INT PRIMARY KEY AUTO_INCREMENT,
    col2 BOOLEAN NOT NULL,
    col3 DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE table1 ADD COLUMN col4 VARCHAR(3) NOT NULL;

RENAME TABLE table1 TO table2;

ALTER TABLE table2 DROP COLUMN col3;
ALTER TABLE table2 MODIFY col4 INT;
ALTER TABLE table2 MODIFY col4 INT COMMENT 'Enter age';

RENAME TABLE table1 TO table2;
SHOW TABLES;